version: '3.1'
services:
    php:
        image: 'php:7.4'
        volumes:
            - ".:/var/www/html"
        working_dir: '/var/www/html'
    composer:
        image: 'composer:latest'
        volumes:
            - ".:/var/www/html"
        working_dir: '/var/www/html'

